Sun Feb 17 15:11:35 CET 2019 : Apache Derby Network Server - 10.11.1.2 - (1629631) démarré et prêt à accepter les connexions sur le port 1527
----------------------------------------------------------------
Sun Feb 17 15:11:36 CET 2019:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance a816c00e-0168-fbcc-338d-0000328ff68e 
dans le répertoire de base de données D:\Ecole\3e année\JSP\JSP-master\DataBases\derby avec le chargeur de classe jdk.internal.loader.ClassLoaders$AppClassLoader@6e5e91e4
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_172/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11+28
user.dir=C:\Program Files\Java\jdk1.8.0_172\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=D:\Ecole\3e année\JSP\JSP-master\DataBases
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
----------------------------------------------------------------
Sun Feb 17 15:11:37 CET 2019:
Fermeture de l'instance a816c00e-0168-fbcc-338d-0000328ff68e sur le répertoire de base de données D:\Ecole\3e année\JSP\JSP-master\DataBases\derby avec le chargeur de classe jdk.internal.loader.ClassLoaders$AppClassLoader@6e5e91e4 
Sun Feb 17 15:11:37 CET 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = derby), (DRDAID = {2}), Arrêt de la base de données 'derby'.
Sun Feb 17 15:11:48 CET 2019 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: Base de données 'sample' introuvable.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Base de données 'sample' introuvable.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Base de données 'sample' introuvable.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Sun Feb 17 15:11:48 CET 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = sample), (DRDAID = {3}), Base de données 'sample' introuvable.
----------------------------------------------------------------
Sun Feb 17 15:11:59 CET 2019:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance a65c80ac-0168-fbcc-338d-0000328ff68e 
dans le répertoire de base de données D:\Ecole\3e année\JSP\JSP-master\DataBases\derby avec le chargeur de classe jdk.internal.loader.ClassLoaders$AppClassLoader@6e5e91e4
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_172/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11+28
user.dir=C:\Program Files\Java\jdk1.8.0_172\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=D:\Ecole\3e année\JSP\JSP-master\DataBases
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
